### ISSUE TITLE
Get error 401	Unauthorized	No or invalid access token

### ISSUE THREAD

**Issue by onkelfarmor** [gkreitz/homeassistant-bosch_dryer#2]
After a while my sensors are no longer updating and in the log I see error code 401. 

As to https://developer.home-connect.com/docs/general/apierrors the code means Unauthorized	No or invalid access token. 

Restart helps, so it looks like the token is not getting refreshed.

**Comment by gkreitz** [comment]
Thanks for the bug report. Fixed in 62fa8f8
